$pdflatex = "pdflatex -file-line-error -halt-on-error -interaction=nonstopmode -synctex=1";

# vim: set filetype=perl:

# Use lualatex
$pdf_mode = 4;
set_tex_cmds('-synctex=1 -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape %O %S');
# Try 5 times at maximum then give up
$max_repeat = 5;
# Use PDF Expert.app to preview generated PDFs
$pdf_previewer = 'open -a "okular"';
# File extensions to remove when cleaning
# Ref: https://www.gitignore.io/api/latex
my @clean_ext = qw(
  %R-blx.aux
  %R-blx.bib
  _minted-%R
  acn
  acr
  alg
  aux
  bbl
  bcf
  blg
  brf
  cb
  cb2
  cpt
  cut
  dvi
  fdb_latexmk
  fls
  fmt
  fot
  glg
  glo
  gls
  glsdefs
  idx
  ilg
  ind
  ist
  lb
  listing
  loa
  loe
  lof
  log
  lol
  lot
  lox
  nav
  out
  pdfsync
  pre
  run.xml
  snm
  soc
  synctex
  synctex(busy)
  synctex.gz
  synctex.gz(busy)
  tdo
  thm
  toc
  upa
  upb
  vrb
  xcp
  xdv
  xmpi
  xyc
  **/*-converted-to.*
);
$clean_ext = join ' ', @clean_ext;

no warnings 'redefine';